#
# PROGRAM: prog2
# AUTHOR:  Noah Flores
#


labtrain: client.cpp server.cpp
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 client.cpp -o client
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 server.cpp -o server

clean:
	rm -f *.o reduce